**LAB 4 **

In [1]:
import numpy as np
import torch

In [2]:
inputs = np.array([[73,67,43],
                   [91,88,64],
                   [87,134,58],
                   [102,43,37],
                   [69,96,70]],dtype='float32')

In [3]:
targets = np.array([[56],
                    [81],
                    [119],
                    [22],
                    [103]],dtype='float32')

In [4]:
 # Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
print(inputs)
targets = torch.from_numpy(targets)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [5]:
 # Weights and biases
w = torch.randn(1,3,requires_grad =True)
print(w)
b = torch.randn(1,requires_grad=True)
print(b)

tensor([[-1.2800,  0.2152,  0.8560]], requires_grad=True)
tensor([-1.1896], requires_grad=True)


In [6]:
# Define the model
def model(x):
  return torch.mm(x,w.t(),out=None) +b

In [7]:
# Generate predictions
# Compare with targets

preds = model(inputs)
print("Prediction :",preds)
print("Targets :",targets)

Prediction : tensor([[-43.4072],
        [-43.9534],
        [-34.0701],
        [-90.8284],
        [ -8.9355]], grad_fn=<AddBackward0>)
Targets : tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [8]:
# MSE loss
# Compute loss
def mse(P,T):
  diff = 0
  i=0
  sum=0
  n=len(T)
  for k in range(0,n):
    i+=1
    diff = T[k] - P[k]
    square = diff*diff
    sum+=square
  mean = sum/i
  return mean

output = mse(preds,targets)
print("Loss :",output)

Loss : tensor([14837.0811], grad_fn=<DivBackward0>)


In [9]:
# Compute gradients
print("Gradient :",output.backward())

Gradient : None


In [10]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[-1.2800,  0.2152,  0.8560]], requires_grad=True)
tensor([[-20470.6543, -21506.0020, -13263.8906]])


In [11]:
# Gradients for bias
print(b)
print(b.grad)

tensor([-1.1896], requires_grad=True)
tensor([-240.8779])


In [12]:
# Compute gradients
with torch.no_grad():
  w-=w.grad*1e-5
  b-=b.grad*1e-5
  w.grad.zero_()
  b.grad.zero_()
print(w)
print(b)

tensor([[-1.0753,  0.4303,  0.9886]], requires_grad=True)
tensor([-1.1872], requires_grad=True)


In [13]:
# Generate predictions
# Calculate the loss
new_preds = model(inputs)
new_loss = mse(new_preds,targets)
print("New Loss :",new_loss)

New Loss : tensor([6155.4209], grad_fn=<DivBackward0>)


In [14]:
# Train for 100 epochs
for i in range(200):
  preds = model(inputs)
  loss = mse(preds,targets)
  loss.backward()
  with torch.no_grad():
    w-=w.grad * 1e-5
    b-=b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [15]:
# Calculate loss
preds = model(inputs)
loss = mse(preds,targets)
print(loss)

tensor([15.3325], grad_fn=<DivBackward0>)


Pytorch_Built_Ins

In [16]:
 # Imports
import torch.nn as nn
print(inputs)
print(targets)


tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [17]:
def model1(x):
  return x @ w.t() +b

In [18]:
preds = model(inputs)
print("Prediction :",preds)
print("Targets :",targets)

Prediction : tensor([[ 56.4881],
        [ 84.8576],
        [113.7492],
        [ 18.6096],
        [107.7411]], grad_fn=<AddBackward0>)
Targets : tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [19]:
loss = nn.MSELoss()
output = loss(preds,targets)
output.backward()
print("Loss :",output)

Loss : tensor(15.3325, grad_fn=<MseLossBackward0>)


In [20]:
print(w)
print(w.grad)
print(b)
print(b.grad)

tensor([[-0.4912,  0.7223,  1.0497]], requires_grad=True)
tensor([[-35.5317,  -8.8301,  67.9044]])
tensor([-1.1824], requires_grad=True)
tensor([0.1782])


In [21]:
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [22]:
preds = model1(inputs)
loss = mse(preds,targets)
 
print(loss)

tensor([10.6492], grad_fn=<DivBackward0>)
